
file(TO_CMAKE_PATH "${CMAKE_CURRENT_LIST_DIR}/.." TCLGRAPHS_BASEDIR)
message(STATUS "Finding TclGraphs ${TCLGRAPHS_VERSION} in ${TCLGRAPHS_BASEDIR} ...")

find_path(TCLGRAPHS_INCLUDE_PATH
	NAMES graphs.h
	HINTS "${TCLGRAPHS_BASEDIR}/include"
)
find_library(TCLGRAPHS_STUB_LIBRARY
	NAMES graphsstub
	PATHS "${TCLGRAPHS_BASEDIR}/lib"
)

set(TCLGRAPHS_DEFINES -DUSE_GRAPHS_STUBS=1 -DTCLGRAPHS_VERSION="${TCLGRAPHS_VERSION}")

mark_as_advanced(
	TCLGRAPHS_DEFINES
	TCLGRAPHS_INCLUDE_DIR
	TCLGRAPHS_STUB_LIBRARY
)
