
set(TCLGRAPHS_BASEDIR "${CMAKE_CURRENT_LIST_DIR}/..")

find_path(TCLGRAPHS_INCLUDE_PATH
	NAMES graphs.h
	HINTS "${TCLGRAPHS_BASEDIR}/include"
)
find_library(TCLGRAPHS_STUB_LIBRARY
	NAMES graphsstub
	PATHS "${TCLGRAPHS_BASEDIR}/lib"
)

set(TCLGRAPHS_DEFINES -DUSE_GAPHS_STUBS=1)

mark_as_advanced(
	TCLGRAPHS_DEFINES
	TCLGRAPHS_INCLUDE_DIR
	TCLGRAPHS_STUB_LIBRARY
)
